apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: poac-pm-certificate
  namespace: default
spec:
  secretName: poac-pm-certificate  # Ingressから参照するシークレット名
  issuerRef:
    name: letsencrypt-issuer  # Issuer name
    kind: Issuer
  commonName: 'poac.pm'  # domain name
  dnsNames:
  - poac.pm  # domain name
  acme:
    config:
    - dns01:
        provider: route53  # Issuerのprovider名
      domains:
      - '*.poac.pm'  # domain name
      - poac.pm
